ERROR:root:this is an error in test2.py
